[2024-12-22T14:59:15.016+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T14:59:15.154+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T14:55:10.356955+00:00 [queued]>
[2024-12-22T14:59:15.239+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T14:55:10.356955+00:00 [queued]>
[2024-12-22T14:59:15.244+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-22T14:59:15.362+0000] {taskinstance.py:2889} INFO - Executing <Task(ShortCircuitOperator): check_date_exists> on 2024-12-22 14:55:10.356955+00:00
[2024-12-22T14:59:15.404+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T14:59:15.433+0000] {standard_task_runner.py:72} INFO - Started process 205 to run task
[2024-12-22T14:59:15.435+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_top_best_sellers_books', 'check_date_exists', 'manual__2024-12-22T14:55:10.356955+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpmuv4hm8r']
[2024-12-22T14:59:15.458+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask check_date_exists
[2024-12-22T14:59:18.478+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T14:55:10.356955+00:00 [running]> on host c50092bbd7fa
[2024-12-22T14:59:19.042+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_top_best_sellers_books' AIRFLOW_CTX_TASK_ID='check_date_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T14:55:10.356955+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-22T14:55:10.356955+00:00'
[2024-12-22T14:59:19.057+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T14:59:19.191+0000] {baseoperator.py:421} WARNING - ShortCircuitOperator.execute cannot be called outside TaskInstance!
[2024-12-22T14:59:19.272+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T14:59:19.297+0000] {sql.py:553} INFO - Running statement: SELECT COUNT(*) FROM date_dim WHERE date = %s;, parameters: ('20241222',)
[2024-12-22T14:59:19.318+0000] {sql.py:562} INFO - Rows affected: 1
[2024-12-22T14:59:19.322+0000] {dag_test.py:69} INFO - Date 20241222 does not exist in date_dim. Proceeding with data load.
[2024-12-22T14:59:19.327+0000] {python.py:240} INFO - Done. Returned value was: True
[2024-12-22T14:59:19.334+0000] {python.py:309} INFO - Condition result is True
[2024-12-22T14:59:19.338+0000] {python.py:312} INFO - Proceeding with downstream tasks...
[2024-12-22T14:59:19.466+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T14:59:19.481+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_top_best_sellers_books, task_id=check_date_exists, run_id=manual__2024-12-22T14:55:10.356955+00:00, execution_date=20241222T145510, start_date=20241222T145915, end_date=20241222T145919
[2024-12-22T14:59:19.606+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-22T14:59:21.037+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-12-22T14:59:21.143+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-22T14:59:21.154+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
