[2024-12-22T15:57:33.558+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T15:57:33.603+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T14:55:10.356955+00:00 [queued]>
[2024-12-22T15:57:33.623+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T14:55:10.356955+00:00 [queued]>
[2024-12-22T15:57:33.624+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2024-12-22T15:57:33.659+0000] {taskinstance.py:2889} INFO - Executing <Task(ShortCircuitOperator): check_date_exists> on 2024-12-22 14:55:10.356955+00:00
[2024-12-22T15:57:33.689+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=785) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T15:57:33.703+0000] {standard_task_runner.py:72} INFO - Started process 788 to run task
[2024-12-22T15:57:33.708+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_top_best_sellers_books', 'check_date_exists', 'manual__2024-12-22T14:55:10.356955+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpzxytdgo4']
[2024-12-22T15:57:33.732+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask check_date_exists
[2024-12-22T15:57:34.421+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_top_best_sellers_books.check_date_exists manual__2024-12-22T14:55:10.356955+00:00 [running]> on host c50092bbd7fa
[2024-12-22T15:57:34.620+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_top_best_sellers_books' AIRFLOW_CTX_TASK_ID='check_date_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T14:55:10.356955+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-22T14:55:10.356955+00:00'
[2024-12-22T15:57:34.625+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T15:57:34.662+0000] {baseoperator.py:421} WARNING - ShortCircuitOperator.execute cannot be called outside TaskInstance!
[2024-12-22T15:57:34.688+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T15:57:34.703+0000] {sql.py:553} INFO - Running statement: SELECT COUNT(*) FROM date_dim WHERE date = %s;, parameters: ('20241222',)
[2024-12-22T15:57:34.708+0000] {sql.py:562} INFO - Rows affected: 1
[2024-12-22T15:57:34.719+0000] {dag_test.py:71} INFO - Date 20241222 does not exist in date_dim. Proceeding with data load.
[2024-12-22T15:57:34.722+0000] {python.py:240} INFO - Done. Returned value was: True
[2024-12-22T15:57:34.727+0000] {python.py:309} INFO - Condition result is True
[2024-12-22T15:57:34.730+0000] {python.py:312} INFO - Proceeding with downstream tasks...
[2024-12-22T15:57:34.836+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T15:57:34.864+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_top_best_sellers_books, task_id=check_date_exists, run_id=manual__2024-12-22T14:55:10.356955+00:00, execution_date=20241222T145510, start_date=20241222T155733, end_date=20241222T155734
[2024-12-22T15:57:35.028+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-22T15:57:36.181+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-22T15:57:36.188+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
