[2024-12-22T15:57:11.078+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T15:57:11.146+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.check_date_exists scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-22T15:57:11.181+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.check_date_exists scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-22T15:57:11.185+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-22T15:57:11.228+0000] {taskinstance.py:2889} INFO - Executing <Task(ShortCircuitOperator): check_date_exists> on 2024-12-15 00:00:00+00:00
[2024-12-22T15:57:11.315+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=773) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T15:57:11.326+0000] {standard_task_runner.py:72} INFO - Started process 776 to run task
[2024-12-22T15:57:11.326+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_top_best_sellers_books', 'check_date_exists', 'scheduled__2024-12-15T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmphlgc7rkm']
[2024-12-22T15:57:11.338+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask check_date_exists
[2024-12-22T15:57:12.097+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_top_best_sellers_books.check_date_exists scheduled__2024-12-15T00:00:00+00:00 [running]> on host c50092bbd7fa
[2024-12-22T15:57:12.611+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_top_best_sellers_books' AIRFLOW_CTX_TASK_ID='check_date_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-15T00:00:00+00:00'
[2024-12-22T15:57:12.619+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T15:57:12.765+0000] {baseoperator.py:421} WARNING - ShortCircuitOperator.execute cannot be called outside TaskInstance!
[2024-12-22T15:57:14.475+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T15:57:14.537+0000] {sql.py:553} INFO - Running statement: SELECT COUNT(*) FROM date_dim WHERE date = %s;, parameters: ('20241215',)
[2024-12-22T15:57:14.560+0000] {sql.py:562} INFO - Rows affected: 1
[2024-12-22T15:57:14.574+0000] {dag_test.py:71} INFO - Date 20241215 does not exist in date_dim. Proceeding with data load.
[2024-12-22T15:57:14.585+0000] {python.py:240} INFO - Done. Returned value was: True
[2024-12-22T15:57:14.600+0000] {python.py:309} INFO - Condition result is True
[2024-12-22T15:57:14.615+0000] {python.py:312} INFO - Proceeding with downstream tasks...
[2024-12-22T15:57:14.800+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T15:57:14.805+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_top_best_sellers_books, task_id=check_date_exists, run_id=scheduled__2024-12-15T00:00:00+00:00, execution_date=20241215T000000, start_date=20241222T155711, end_date=20241222T155714
[2024-12-22T15:57:14.866+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-22T15:57:19.683+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-12-22T15:57:19.996+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-22T15:57:20.023+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
