[2024-12-22T17:16:42.209+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T17:16:43.576+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.load_data_to_postgres scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-22T17:16:44.237+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_top_best_sellers_books.load_data_to_postgres scheduled__2024-12-15T00:00:00+00:00 [queued]>
[2024-12-22T17:16:44.251+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-22T17:16:44.731+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2024-12-15 00:00:00+00:00
[2024-12-22T17:16:45.273+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1459) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T17:16:45.381+0000] {standard_task_runner.py:72} INFO - Started process 1476 to run task
[2024-12-22T17:16:45.635+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_top_best_sellers_books', 'load_data_to_postgres', 'scheduled__2024-12-15T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpodp_oljb']
[2024-12-22T17:16:46.097+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask load_data_to_postgres
[2024-12-22T17:16:55.080+0000] {job.py:229} INFO - Heartbeat recovered after 18.86 seconds
[2024-12-22T17:18:14.515+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_top_best_sellers_books.load_data_to_postgres scheduled__2024-12-15T00:00:00+00:00 [running]> on host c50092bbd7fa
[2024-12-22T17:18:18.374+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_top_best_sellers_books' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-15T00:00:00+00:00'
[2024-12-22T17:18:18.479+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T17:18:19.019+0000] {job.py:229} INFO - Heartbeat recovered after 59.13 seconds
[2024-12-22T17:18:24.548+0000] {dag_test.py:51} ERROR - {'author_dim':                      Author  author_id
0                Paperback,          1
1          Martin Kleppmann          2
2               Alex Petrov          3
3   Cole Nussbaumer Knaflic          4
4            Charity Majors          5
5               Jay Wengrow          6
6                   Kindle,          7
7          Catherine Nelson          8
8            James Densmore          9
9             Scott E. Page         10
10            Bill Chambers         11
11        Steven L. Brunton         12
12               Hardcover,         13
13         Robert S. Seiner         14
14              Kevin Kelly         15
15             James Gleick         16
16            Kevin Mitnick         17
17           Wilpen L. Gorr         18
18              Bill Karwin         19
19            Kenneth Field         20
20          Allen B. Downey         21
21                   Kindle         22
22            Stefan Jansen         23
23         Michael P. Lynch         24
24       Bradford Tuckfield         25
25       Audible Audiobook,         26
26                Paperback         27
27               eTextbook,         28
28           Tamer Khraisha         29
29            Alan Beaulieu         30
30         John Ladley B.A.         31
31             Jeff Prosise         32
32             Hannes Hapke         33
33       Ole Olesen-Bagneux         34
34            Pulkit Chadha         35
35            Andy Petrella         36
36             Dan Sullivan         37
37            Paul Crickard         38
38      Piethein Strengholt         39
39     Mehdi Nourbakhsh PhD         40
40            Chris Okasaki         41
41        Giacinto Palmieri         42
42           Alex Kolokolov         43
43             Paul Iusztin         44, 'date_dim':         Date  date_id  year  month  day
0 2024-12-22        1  2024     12   22, 'books':     author_id  ...  book_id
0           1  ...        1
1           2  ...        2
2           3  ...        3
3           4  ...        4
4           5  ...        5
5           6  ...        6
6           7  ...        7
7           1  ...        8
8           8  ...        9
9           9  ...       10
10         10  ...       11
11         11  ...       12
12         12  ...       13
13         13  ...       14
14          1  ...       15
15         14  ...       16
16         15  ...       17
17          1  ...       18
18         16  ...       19
19          1  ...       20
20         17  ...       21
21         18  ...       22
22         19  ...       23
23         13  ...       24
24         20  ...       25
25         21  ...       26
26         22  ...       27
27         23  ...       28
28         24  ...       29
29         25  ...       30
30         26  ...       31
31         27  ...       32
32         28  ...       33
33         29  ...       34
34         30  ...       35
35         31  ...       36
36         22  ...       37
37         32  ...       38
38         33  ...       39
39         34  ...       40
40         35  ...       41
41         36  ...       42
42         37  ...       43
43         38  ...       44
44         39  ...       45
45         40  ...       46
46         41  ...       47
47         42  ...       48
48         43  ...       49
49         44  ...       50

[50 rows x 7 columns]}
[2024-12-22T17:18:26.273+0000] {dag_test.py:52} WARNING - <class 'dict'>
[2024-12-22T17:18:26.482+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T17:18:26.925+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T17:18:27.191+0000] {base.py:84} INFO - Retrieving connection 'books_connection'
[2024-12-22T17:18:27.414+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_test.py", line 61, in load_data_to_postgres
    insert_to_postgres('date_dim', pd.DataFrame(transformed_data['date_dim']), postgres_conn_id)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/insert_to_postgres.py", line 23, in insert_to_postgres
    cursor.execute(query)
psycopg2.errors.SyntaxError: syntax error at or near "s"
LINE 1: ...4.7 out of 5 stars', 'Storytelling with Data: Let's Practice...
                                                             ^

[2024-12-22T17:18:27.702+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_top_best_sellers_books, task_id=load_data_to_postgres, run_id=scheduled__2024-12-15T00:00:00+00:00, execution_date=20241215T000000, start_date=20241222T171643, end_date=20241222T171827
[2024-12-22T17:18:28.087+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T17:18:28.115+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 47 for task load_data_to_postgres (syntax error at or near "s"
LINE 1: ...4.7 out of 5 stars', 'Storytelling with Data: Let's Practice...
                                                             ^
; 1476)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_test.py", line 61, in load_data_to_postgres
    insert_to_postgres('date_dim', pd.DataFrame(transformed_data['date_dim']), postgres_conn_id)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/insert_to_postgres.py", line 23, in insert_to_postgres
    cursor.execute(query)
psycopg2.errors.SyntaxError: syntax error at or near "s"
LINE 1: ...4.7 out of 5 stars', 'Storytelling with Data: Let's Practice...
                                                             ^

[2024-12-22T17:18:28.720+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-22T17:18:28.959+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-12-22T17:18:29.227+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-22T17:18:29.291+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
